from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class ToolSpec:
    name: str
    description: str
    parameters: dict[str, Any]


class WorldAdapter(Protocol):
    def list_tools(self) -> list[ToolSpec]: ...
    def start_session(self, session_id: str) -> None: ...
    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> Any: ...
    def snapshot(self) -> dict[str, Any]: ...
    def evaluate_run(self, session_runs: list[Any]) -> dict[str, Any]: ...
    def prompt_rules(self) -> list[str]: ...
    def close(self) -> None: ...

